# Generated by Django 5.2.17 on 2026-09-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_protect_exclusao'),
        ('matricula', '0001_initial'),
        ('turma', '0003_protect_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turma.turma'),
        ),
    ]
