# Generated by Django 5.2.17 on 2026-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_protect_exclusao'),
        ('matricula', '0002_protect_exclusao'),
        ('turma', '0004_turma_unica_ano_atual'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ativo', 'pendente'])), fields=('aluno', 'ano_letivo'), name='uma_matricula_vigente_por_ano'),
        ),
    ]
