# Generated by Django 5.2.17 on 2026-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretario', 'Secretário'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('responsavel', 'Responsável')], default='aluno', max_length=20),
        ),
    ]
