# Generated by Django 5.0 on 2026-09-30 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('responsavel', 'Responsável')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
            },
        ),
    ]
