# Generated by Django 5.2.17 on 2026-09-30 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'responsavel'}, related_name='dependentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
