# Generated by Django 5.2.17 on 2026-09-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_responsaveis'),
        ('turma', '0003_protect_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turma.turma'),
        ),
    ]
