# Generated by Django 5.0 on 2026-09-30 04:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='professor', max_length=100)),
                ('cpf', models.CharField(default='99999999999', max_length=11)),
                ('rg', models.CharField(default='9999999', max_length=7)),
                ('orgao_expedidor', models.CharField(default='INSTITUTO FEDERAL', max_length=20)),
                ('data_nascimento', models.DateField(default=datetime.date(1999, 1, 1))),
                ('endereco', models.CharField(default='S/N', max_length=200)),
                ('telefone_contato', models.CharField(default='+559999999999', max_length=20)),
                ('email', models.EmailField(default='email@teste.com', max_length=254)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('naturalidade', models.CharField(default='Brasil', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/')),
                ('disciplinas', models.ManyToManyField(blank=True, to='disciplina.disciplina')),
            ],
        ),
    ]
