# Generated by Django 5.2.17 on 2026-09-30 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
