"""
Django settings for smartsecretaria project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dotenv
# Configurações do SimpleJWT
from datetime import timedelta

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(nome, padrao=False):
    valor = os.getenv(nome)
    return padrao if valor is None else valor.strip().lower() in ('1', 'true', 'sim', 'yes', 'on')


def env_lista(nome, padrao=''):
    """Lista separada por vírgulas, ignorando itens vazios."""
    return [item.strip() for item in os.getenv(nome, padrao).split(',') if item.strip()]


# Toda configuração que muda entre ambientes vem de variáveis de ambiente
# (arquivo .env local ou painel do provedor). Os padrões servem ao desenvolvimento local.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

ALLOWED_HOSTS = env_lista('ALLOWED_HOSTS', 'localhost,127.0.0.1')
# O Render informa o domínio público do serviço nesta variável.
if os.getenv('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])


# Application definition

INSTALLED_APPS = [
    # Aplicativos Django existentes
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplicativos de terceiros
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    
    # Aplicativos locais
    'core',
    'usuarios',
    'aluno',
    'professor',
    'turma',
    'calendario',
    'matricula',
    'documentos',
    'logs',
    'relatorios',
    'notificacoes',
    'permissoes',
    'disciplina',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    
    # Outros middlewares existentes
    'django.middleware.security.SecurityMiddleware',
    # Serve os arquivos estáticos (admin) em produção, sem servidor extra.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartsecretaria.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartsecretaria.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Caminho configurável: na demo pública o banco é recriado a cada início.
        'NAME': os.getenv('SQLITE_PATH', str(BASE_DIR / 'data' / 'db.sqlite3')),
    },

    #NOTA: instalar o pacote mysqlclient para usar o banco de dados MySQL
    #NOTA: Para usar o banco de dados MySQL, comente o bloco 'default' e descomente o bloco 'mysql' ou migre para os dois bancos de dados digitado o comando: python manage.py migrate --database=mysql
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Somente em `manage.py test`: hash rápido para a suíte não gastar tempo com PBKDF2.
# Nunca afeta o servidor nem senhas reais.
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Uploads (fotos). No plano gratuito do Render o disco é temporário.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))

# HTTPS atrás do proxy do provedor (Render). Ligue com SECURE_HTTPS=true em produção.
if env_bool('SECURE_HTTPS', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'usuarios.CustomUser'

# Login aceita o nome de usuário ou o email da conta.
AUTHENTICATION_BACKENDS = ['usuarios.backends.LoginOuEmailBackend']


# Configurações do Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}


SIMPLE_JWT = {
    # Tempo de expiração do token de acesso
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    
    # Renovação automática e segurança extra
    'ROTATE_REFRESH_TOKENS': True,      # gera novo refresh token a cada uso
    'BLACKLIST_AFTER_ROTATION': True,   # invalida o antigo
    
    # Padrão de autenticação
    'AUTH_HEADER_TYPES': ('Bearer',),

    # Algoritmo de criptografia
    'ALGORITHM': 'HS256',

    # Importante: usa a SECRET_KEY do projeto
    'SIGNING_KEY': SECRET_KEY,

    # Define se o token pode ser usado em vários microsserviços
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
}

# Configurações do DRF-Spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'SmartSecretaria API',
    'DESCRIPTION': 'API para o sistema de gestão escolar SmartSecretaria',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS: endereços do frontend autorizados a chamar a API (ex.: o domínio da Vercel).
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env_lista('CORS_ALLOWED_ORIGINS', 'http://localhost:5173')

# Origens confiáveis para formulários com CSRF (painel /admin em HTTPS).
CSRF_TRUSTED_ORIGINS = env_lista('CSRF_TRUSTED_ORIGINS')
if os.getenv('RENDER_EXTERNAL_HOSTNAME'):
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ['RENDER_EXTERNAL_HOSTNAME']}")
