# Generated by Django 5.0 on 2026-09-30 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(choices=[(1, '1º Período - Educação Infantil'), (2, '2º Período - Educação Infantil'), (3, '1º Ano - Ensino Fundamental I'), (4, '2º Ano - Ensino Fundamental I'), (5, '3º Ano - Ensino Fundamental I'), (6, '4º Ano - Ensino Fundamental I'), (7, '5º Ano - Ensino Fundamental I'), (8, '6º Ano - Ensino Fundamental II'), (9, '7º Ano - Ensino Fundamental II'), (10, '8º Ano - Ensino Fundamental II'), (11, '9º Ano - Ensino Fundamental II'), (12, '1º Ano - Ensino Médio'), (13, '2º Ano - Ensino Médio'), (14, '3º Ano - Ensino Médio')])),
                ('turma_letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2)),
                ('horario_aulas', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.IntegerField(default=2023)),
                ('periodo', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], default='Manhã', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('nivel_ensino_sigla', models.CharField(blank=True, choices=[('EI', 'Educação Infantil'), ('EFI', 'Ensino Fundamental I'), ('EFII', 'Ensino Fundamental II'), ('EM', 'Ensino Médio')], max_length=10)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
        ),
    ]
