# Generated by Django 5.2.17 on 2026-09-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('professor', '0002_professor_usuario'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='disciplina.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='professor.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='turma.turma')),
            ],
            options={
                'verbose_name': 'Disciplina da turma',
                'verbose_name_plural': 'Disciplinas da turma',
                'constraints': [models.UniqueConstraint(fields=('turma', 'disciplina'), name='uma_atribuicao_por_disciplina_na_turma')],
            },
        ),
    ]
