# Generated by Django 5.2.17 on 2026-09-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_usuario'),
        ('turma', '0002_turma_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professor.professor'),
        ),
    ]
