# Generated by Django 5.2.17 on 2026-10-01 00:44

import turma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_data_admissao_localdate'),
        ('turma', '0003_protect_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=turma.models.ano_letivo_atual),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('ano', 'serie', 'turma_letra'), name='turma_unica_no_ano'),
        ),
    ]
